### PR TITLE
Handle Xfce panel Dark-mode and also extra bash command

### PR DESCRIPTION
**Pull request by mikachou**
I propose a commit from the fork I made from this project.
On my repository I added two branches for modifications :
* one for panel dark-mode in Xfce (panel)
* one to handle extra bash command in case you wish execute commands for other gui toolkit (extracmd). For example on manjaro when switching to light theme I execute the following command : 
```
$ kvantummanager --set Matcha-Light
```
and conversely for dark-theme
```
$ kvantummanager --set Matcha-Dark
```
Purpose of these command is to make some Qt apps theme match the GTK Xfce theme (Manjaro kernel manager for example).

I merged these two branches in my own master branch, then now suggest to merge my master branch in your project.

### CODE REVIEW

**Comment by bimlas** [comment]
Sorry for the late reply.

Can you please show me screenshots about the issue with panels? I'm using XFCE 4.16 and the panels are changing colors as expected as you can see in the readme file.

I'm not sure that allowing users to run extra shell commands is still fits to purpose of this plugin, I have to think about this.

**Comment by mikachou** [comment]
Hi,
Thanks for your reply.

About the panel I just wanted to be able to add some extra customization in case of, for some reason, a user want to use light mode with dark panel for example.
Let's add screenshot to illustrate my point :
Dark mode :
Capture d’écran_2022-11-19_15-41-17
Light mode :
Capture d’écran_2022-11-19_15-42-23
Light mode with dark panel :
Capture d’écran_2022-11-19_16-21-25

That's why I added the ability to customize the xfconf xfce4-panels/panels/dark-mode property (boolean). This property is usually accessible for end-user with right-click on the panel > preferences > appearance (or look?), then there is a button to switch panel dark-mode on/off

Regarding the second point, the extra-command was added because some applications which don't use GTK as UI may not switch to light/dark theme (like some Qt apps)
There are for instance a "Manjaro parameters" menu on Manjaro Linux, accessible through Xfce parameters. In order to make this window have the same look as the rest of the desktop I must add an extra-command to set kvantum with the right theme. To illustrate my point, let's suppose that we are switching from light theme to dark theme, then open the Manjaro parameter sub-menu from Xfce parameters.
What we have with the kvantummanager extra command :

Capture d’écran_2022-11-19_15-51-03
What we have without the kvantummanager extra command :
Capture d’écran_2022-11-19_15-52-03

In the second illustration, we can see that the Manjaro sub-menu has still the light-theme whereas the rest of the desktop has the dark-theme. Thus I added extra-command parameter to solve this issue.

Finally, but it may a bit off-topic, I also wondered if it may not be useful to have the ability to change desktop background while switching light/dark, but I haven't implemented yet, because I actually didn't really need it.

**Comment by mikachou** [comment]
Here is what you have with dark-panel on light-theme with right icon-theme, but you have the idea :
Capture d’écran_2022-11-19_16-21-25
And that may be a bit off topic, but I wonder if the ability to change desktop background may not also be useful (but I haven't implemented yet)

**Comment by bimlas** [comment]
Sorry for the late reply.

I have to decline this PR, because it's too specific modification in my opinion. We could add a lot of options to the script, because a lot of apps have day / night mode. Instead of making the script almighty, I let the user execute any command that he/she wants: https://github.com/bimlas/xfce4-night-mode#settings -> `UserScript`

**EDIT**

Just realized that I did almost the same with the `UserScript` as you did with `EXTRACMD`, so basically your PR was correct, I was inattentive, really sorry, it's late here. You can find instructions about changing the wallpaper in the readme.

**Pull request closed without merging**
